openapi: 3.0.3
info:
  title: Product Directory
  description: |
    This API is used to synchronise products, categories and hierarchies between external system and Product Directory.
  version: 1.3.0
  x-icon: people
  x-api-domain: product-management
  x-api-service: product-directory
servers:
- url: http://localhost:8080
tags:
- name: Retail
- name: Business
paths:
  /integration-api/v1/products/{productKey}:
    patch:
      tags:
      - Products
      summary: Update a product
      operationId: updateProduct
      parameters:
      - name: productKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: "#/components/schemas/ProductKey"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateProductPayload"
        required: true
      responses:
        "200":
          description: Product updated successfully
        "400":
          $ref: "#/components/responses/400BadRequest"
        "404":
          $ref: "#/components/responses/404NotFound"
  /integration-api/v1/products:
    get:
      tags:
      - Products
      summary: Get list of products
      operationId: getProducts
      parameters:
      - name: page
        in: query
        required: false
        style: form
        explode: true
        schema:
          minimum: 0
          type: integer
          description: Page number.
          example: 10
          default: 0
      - name: perPage
        in: query
        required: false
        style: form
        explode: true
        schema:
          maximum: 1000
          minimum: 1
          type: integer
          description: Number of items per page.
          example: 10
          default: 20
      responses:
        "200":
          description: Products retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductWithTranslations"
        "400":
          $ref: "#/components/responses/400BadRequest"
    post:
      tags:
      - Products
      summary: Create a product
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateProductPayload"
        required: true
      responses:
        "201":
          description: Product created successfully
        "400":
          $ref: "#/components/responses/400BadRequest"
  /integration-api/v1/categories/{categoryKey}:
    put:
      tags:
      - Categories
      summary: Upsert a category
      operationId: upsertCategory
      parameters:
      - name: categoryKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: "#/components/schemas/CategoryKey"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertCategoryPayload"
        required: true
      responses:
        "200":
          description: Category updated successfully
        "201":
          description: Category created successfully
        "400":
          $ref: "#/components/responses/400BadRequest"
        "409":
          $ref: "#/components/responses/409Conflict"
    delete:
      tags:
      - Categories
      summary: Delete a category
      operationId: deleteCategory
      parameters:
      - name: categoryKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: "#/components/schemas/CategoryKey"
      responses:
        "204":
          description: Category deleted successfully
        "400":
          $ref: "#/components/responses/400BadRequest"
        "404":
          $ref: "#/components/responses/404NotFound"
        "409":
          $ref: "#/components/responses/409Conflict"
  /integration-api/v1/categories/hierarchies/{hierarchyKey}:
    put:
      tags:
      - Hierarchies
      summary: Upsert a hierarchy
      operationId: upsertHierarchy
      parameters:
      - name: hierarchyKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: "#/components/schemas/HierarchyKey"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpsertHierarchyPayload"
        required: true
      responses:
        "200":
          description: Hierarchy updated successfully
        "201":
          description: Hierarchy created successfully
        "400":
          $ref: "#/components/responses/400BadRequest"
    delete:
      tags:
      - Hierarchies
      summary: Delete a hierarchy
      operationId: deleteHierarchy
      parameters:
      - name: hierarchyKey
        in: path
        required: true
        style: simple
        explode: false
        schema:
          $ref: "#/components/schemas/HierarchyKey"
      responses:
        "204":
          description: Hierarchy deleted successfully
        "400":
          $ref: "#/components/responses/400BadRequest"
        "404":
          $ref: "#/components/responses/404NotFound"
components:
  schemas:
    UpdateProductPayload:
      type: object
      properties:
        availabilityStartDate:
          $ref: "#/components/schemas/ProductAvailabilityStartDate"
        availabilityEndDate:
          $ref: "#/components/schemas/ProductAvailabilityEndDate"
        rank:
          $ref: "#/components/schemas/ProductRank"
      description: Update product payload
    CreateProductPayload:
      required:
      - availabilityStartDate
      - categories
      - descriptions
      - externalProductId
      - faqs
      - features
      - linkGroups
      - name
      - productKey
      type: object
      properties:
        externalProductId:
          $ref: "#/components/schemas/ExternalProductId"
        productKey:
          $ref: "#/components/schemas/ProductKey"
        templateKey:
          $ref: "#/components/schemas/TemplateKey"
        name:
          $ref: "#/components/schemas/ProductName"
        availabilityStartDate:
          $ref: "#/components/schemas/ProductAvailabilityStartDate"
        availabilityEndDate:
          $ref: "#/components/schemas/ProductAvailabilityEndDate"
        rank:
          $ref: "#/components/schemas/ProductRank"
        icon:
          $ref: "#/components/schemas/Icon"
        linkGroups:
          type: array
          description: Group of links related to the product
          items:
            $ref: "#/components/schemas/LinkGroupWithTranslations"
        categories:
          minItems: 1
          type: array
          description: Keys of categories associated with the product
          items:
            $ref: "#/components/schemas/CategoryKey"
        faqs:
          type: array
          description: FAQ sections related to the product
          items:
            $ref: "#/components/schemas/FaqWithTranslations"
        descriptions:
          type: array
          description: Descriptions associated with the product
          items:
            $ref: "#/components/schemas/DescriptionWithTranslations"
        features:
          type: array
          description: Product feature list
          items:
            $ref: "#/components/schemas/FeatureWithTranslations"
        translations:
          $ref: "#/components/schemas/Translations"
        additions:
          $ref: "#/components/schemas/Additions"
      description: Create product payload
    UpsertCategoryPayload:
      required:
      - additionalDescriptions
      - externalCategoryId
      - name
      type: object
      properties:
        externalCategoryId:
          $ref: "#/components/schemas/ExternalCategoryId"
        name:
          $ref: "#/components/schemas/CategoryName"
        description:
          $ref: "#/components/schemas/CategoryDescription"
        icon:
          $ref: "#/components/schemas/Icon"
        additionalDescriptions:
          type: array
          description: Additional descriptions for the category
          items:
            $ref: "#/components/schemas/CategoryAdditionalDescriptionWithTranslations"
        translations:
          $ref: "#/components/schemas/Translations"
        additions:
          $ref: "#/components/schemas/Additions"
      description: Upsert category payload
    UpsertHierarchyPayload:
      required:
      - roots
      type: object
      properties:
        roots:
          type: array
          description: Top-level categories in hierarchy
          items:
            $ref: "#/components/schemas/UpsertHierarchyPayloadHierarchyNode"
        additions:
          $ref: "#/components/schemas/Additions"
      description: Upsert hierarchy payload
    UpsertHierarchyPayloadHierarchyNode:
      required:
      - category
      - subCategories
      type: object
      properties:
        category:
          $ref: "#/components/schemas/CategoryKey"
        subCategories:
          type: array
          description: Sub-categories of category in the hierarchy
          items:
            $ref: "#/components/schemas/UpsertHierarchyPayloadHierarchyNode"
      description: Upsert hierarchy payload hierarchy node
    ProductWithTranslations:
      required:
      - availabilityStartDate
      - categories
      - descriptions
      - externalProductId
      - faqs
      - features
      - internalProductId
      - linkGroups
      - name
      - productKey
      type: object
      properties:
        internalProductId:
          $ref: "#/components/schemas/InternalProductId"
        externalProductId:
          $ref: "#/components/schemas/ExternalProductId"
        productKey:
          $ref: "#/components/schemas/ProductKey"
        templateKey:
          $ref: "#/components/schemas/TemplateKey"
        name:
          $ref: "#/components/schemas/ProductName"
        availabilityStartDate:
          $ref: "#/components/schemas/ProductAvailabilityStartDate"
        availabilityEndDate:
          $ref: "#/components/schemas/ProductAvailabilityEndDate"
        rank:
          $ref: "#/components/schemas/ProductRank"
        createdAt:
          $ref: "#/components/schemas/ProductCreatedAtDate"
        lastUpdatedAt:
          $ref: "#/components/schemas/ProductLastUpdatedAtDate"
        icon:
          $ref: "#/components/schemas/Icon"
        linkGroups:
          type: array
          description: Group of links related to the product
          items:
            $ref: "#/components/schemas/LinkGroupWithTranslations"
        faqs:
          type: array
          description: FAQ sections related to the product
          items:
            $ref: "#/components/schemas/FaqWithTranslations"
        descriptions:
          type: array
          description: Descriptions associated with the product
          items:
            $ref: "#/components/schemas/DescriptionWithTranslations"
        features:
          type: array
          description: Product feature list
          items:
            $ref: "#/components/schemas/FeatureWithTranslations"
        categories:
          type: array
          description: Categories associated with the product
          items:
            $ref: "#/components/schemas/CategoryWithTranslations"
        translations:
          $ref: "#/components/schemas/Translations"
        additions:
          $ref: "#/components/schemas/Additions"
      description: Product with translations
    CategoryWithTranslations:
      required:
      - additionalDescriptions
      - categoryKey
      - externalCategoryId
      - internalCategoryId
      - name
      type: object
      properties:
        internalCategoryId:
          $ref: "#/components/schemas/InternalCategoryId"
        externalCategoryId:
          $ref: "#/components/schemas/ExternalCategoryId"
        categoryKey:
          $ref: "#/components/schemas/CategoryKey"
        name:
          $ref: "#/components/schemas/CategoryName"
        description:
          $ref: "#/components/schemas/CategoryDescription"
        icon:
          $ref: "#/components/schemas/Icon"
        additionalDescriptions:
          type: array
          description: Additional descriptions for the category
          items:
            $ref: "#/components/schemas/CategoryAdditionalDescriptionWithTranslations"
        translations:
          $ref: "#/components/schemas/Translations"
        additions:
          $ref: "#/components/schemas/Additions"
      description: Category with translations
    CategoryAdditionalDescriptionWithTranslations:
      allOf:
      - $ref: "#/components/schemas/CategoryAdditionalDescriptionBase"
      - type: object
        properties:
          translations:
            $ref: "#/components/schemas/Translations"
    FeatureWithTranslations:
      description: Product feature with translations
      allOf:
      - $ref: "#/components/schemas/FeatureBase"
      - type: object
        properties:
          translations:
            $ref: "#/components/schemas/Translations"
    DescriptionWithTranslations:
      description: Product description with translations
      allOf:
      - $ref: "#/components/schemas/DescriptionBase"
      - type: object
        properties:
          translations:
            $ref: "#/components/schemas/Translations"
    FaqWithTranslations:
      required:
      - faqItems
      - faqKey
      type: object
      properties:
        faqKey:
          $ref: "#/components/schemas/FAQKey"
        faqItems:
          minItems: 1
          type: array
          description: List of questions and answers in the faq
          items:
            allOf:
            - $ref: "#/components/schemas/FAQItemBase"
            - type: object
              properties:
                translations:
                  $ref: "#/components/schemas/Translations"
      description: Product FAQ with translations
    LinkGroupWithTranslations:
      required:
      - groupKey
      - links
      type: object
      properties:
        groupKey:
          $ref: "#/components/schemas/LinkGroupKey"
        links:
          minItems: 1
          type: array
          description: List of links in the group
          items:
            allOf:
            - $ref: "#/components/schemas/LinkBase"
            - type: object
              properties:
                translations:
                  $ref: "#/components/schemas/Translations"
      description: Product link group with translations
    ProductKey:
      maxLength: 255
      minLength: 1
      type: string
      description: Unique key of the product
      example: mortgage-2025-05-fixed-term
    CategoryKey:
      maxLength: 255
      minLength: 1
      type: string
      description: "Unique, immutable key of the category"
      example: cards
    HierarchyKey:
      maxLength: 255
      minLength: 1
      type: string
      description: "Unique, immutable key of the hierarchy"
      example: retail-products
    error:
      title: Error
      required:
      - key
      - message
      type: object
      properties:
        message:
          minLength: 1
          type: string
          description: Any further information
        key:
          minLength: 1
          type: string
          description: Error summary
        errors:
          type: array
          description: Detailed error information
          items:
            $ref: "#/components/schemas/error-item"
    ProductAvailabilityStartDate:
      type: string
      description: Start date of product availability
      format: date-time
      example: 2025-06-01T00:00:00Z
    ProductAvailabilityEndDate:
      type: string
      description: End date of product availability
      format: date-time
      example: 2025-12-01T23:59:59Z
    ProductRank:
      type: number
      description: The product rank. Supports decimal numbers (e.g. 11.05) to allow
        inserting items between existing ranks without reshuffling.
    ExternalProductId:
      maxLength: 255
      minLength: 1
      type: string
      description: Unique external product identifier
      example: ext-id-001
    TemplateKey:
      maxLength: 255
      type: string
      description: Template key identifier
      example: mortgages-fixed-term-view
    ProductName:
      maxLength: 150
      minLength: 1
      type: string
      description: Name of the product
      example: Fixed-Term Mortgage
    Icon:
      maxLength: 2000
      type: string
      description: "Reference of the product icon, typically from a design system\
        \ but can be URL"
      example: product-icon-from-design-system
    Translations:
      type: object
      additionalProperties:
        type: object
        additionalProperties:
          type: string
          description: Object property translation
        description: Object property for which translation is to take place
      description: Locale code following structure defined in BCP 47
      example:
        en-US:
          name: Product
          description: This is product
        fr-FR:
          name: Produit
          description: C'est un produit
    Additions:
      title: Additions
      type: object
      additionalProperties:
        type: string
      description: Additional properties
    ExternalCategoryId:
      maxLength: 255
      minLength: 1
      type: string
      description: Unique external category identifier
      example: ext-id-001
    CategoryName:
      maxLength: 50
      minLength: 1
      type: string
      description: Name of the category
      example: Accounts
    CategoryDescription:
      maxLength: 500
      minLength: 1
      type: string
      description: Description of the category
      example: "Flexible, secure, and easy everyday banking."
    InternalProductId:
      type: string
      description: Internal product identifier
      format: uuid
      example: 58b76042-0e6b-4cec-ad2f-2826c6cc8a4d
    ProductCreatedAtDate:
      type: string
      description: Date of product creation
      format: date-time
      example: 2025-12-01T23:59:59Z
    ProductLastUpdatedAtDate:
      type: string
      description: Date of last product update
      format: date-time
      example: 2025-12-01T23:59:59Z
    InternalCategoryId:
      type: string
      description: Internal category identifier
      format: uuid
      example: 58b76042-0e6b-4cec-ad2f-2826c6cc8a4d
    CategoryAdditionalDescriptionBase:
      required:
      - content
      - type
      type: object
      properties:
        content:
          maxLength: 2000
          minLength: 1
          type: string
          description: Content of the additional description
          example: A mortgage is a long-term loan that helps you turn the keys to
            your dream home into reality.
        type:
          maxLength: 255
          minLength: 1
          type: string
          description: Type of the additional description
          example: tagline
    FeatureBase:
      required:
      - name
      - type
      type: object
      properties:
        name:
          maxLength: 100
          minLength: 1
          type: string
          description: Name of the feature
          example: Surprise Benefit
        description:
          maxLength: 2000
          minLength: 1
          type: string
          description: Description of the feature
          example: Surprise benefit when you apply now!
        type:
          maxLength: 255
          minLength: 1
          type: string
          description: Type of the feature
          example: benefit
        additions:
          $ref: "#/components/schemas/Additions"
    DescriptionBase:
      required:
      - content
      - type
      type: object
      properties:
        type:
          maxLength: 255
          minLength: 1
          type: string
          description: Type of the description
          example: pricing_section_header
        content:
          maxLength: 2000
          minLength: 1
          type: string
          description: Description content
          example: This is the best product.
        additions:
          $ref: "#/components/schemas/Additions"
    FAQKey:
      maxLength: 255
      minLength: 1
      type: string
      description: Key representing the question group
      example: faq-main-section
    FAQItemBase:
      required:
      - answer
      - question
      type: object
      properties:
        question:
          maxLength: 255
          minLength: 1
          type: string
          description: Text of the question
          example: Can I transfer my existing mortgage from another bank?
        answer:
          maxLength: 2000
          minLength: 1
          type: string
          description: Answer to the question
          example: "Yes, you can transfer your existing mortgage from another bank\
            \ to us through a process called a home loan balance transfer. It allows\
            \ you to move your outstanding loan to our bank, often to enjoy better\
            \ interest rates, lower EMIs, or improved loan terms."
        additions:
          $ref: "#/components/schemas/Additions"
    LinkGroupKey:
      maxLength: 255
      minLength: 1
      type: string
      description: Key identifier for the link group
      example: documents
    LinkBase:
      required:
      - name
      - type
      - url
      type: object
      properties:
        type:
          maxLength: 255
          minLength: 1
          type: string
          description: Type of the link
          example: PDF
        name:
          maxLength: 255
          minLength: 1
          type: string
          description: Name of the link
          example: Terms and Conditions
        url:
          type: string
          description: URL to the linked resource
          format: uri
          example: https://cdn.example.com/documents/mortgage-terms-and-conditions.pdf
        additions:
          $ref: "#/components/schemas/Additions"
    error-item:
      title: ErrorItem
      required:
      - key
      - message
      type: object
      properties:
        message:
          minLength: 1
          type: string
          description: Any further information.
        key:
          minLength: 1
          type: string
          description: "{capability-name}.api.{api-key-name}. For generated validation\
            \ errors this is the path in the document the error resolves to. e.g.\
            \ object name + '.' + field"
        context:
          title: Context
          type: object
          additionalProperties:
            type: string
          description: Context can be anything used to construct localised messages.
  responses:
    "400BadRequest":
      description: If one or more request parameters don't comply with the specification
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            $ref: "#/components/examples/bad-request-validation-error"
    "404NotFound":
      description: Not found.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            $ref: "#/components/examples/not-found-error"
    "409Conflict":
      description: Conflict.
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/error"
          example:
            $ref: "#/components/examples/conflict-error"
  examples:
    bad-request-validation-error:
      summary: bad-request-validation-error
      value:
        message: Bad Request
        key: REQUEST_ERROR
        errors:
        - message: "Value Exceeded. Must be between {min} and {max}."
          key: common.api.shoesize
          context:
            max: "50"
            min: "1"
    not-found-error:
      summary: not-found-error
      value:
        message: Resource not found.
        key: NOT_FOUND_ERROR
        errors:
        - message: "Unable to find the requested resource: {resource}."
          key: common.api.resource
          context:
            resource: aResource
    conflict-error:
      summary: conflict-error
      value:
        message: Conflict error
        key: CONFLICT_ERROR
        errors:
        - message: The request could not be completed due to a conflict with the current
            state of the resource.
          key: transactions.api.billingstatus.transaction
          context:
            billingStatus: BILLED
